from langchain_community.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings

from dotenv import load_dotenv

load_dotenv()

from langchain_core.documents import Document

docs = [
    Document(page_content="This is the first document.", metadata={"source": "doc1.txt"}),
    Document(page_content="This is the second document.", metadata={"source": "doc2.txt"}),
    Document(page_content="This is the third document.", metadata={"source": "doc3.txt"}),
]

embedding_model = OpenAIEmbeddings()

vector_store = Chroma.from_documents(
    documents=docs, 
    embedding=embedding_model,
    persist_directory="chroma-db" # local storage
)

result =  vector_store.similarity_search("what is used for data analysis?",k=2) # k is the number of similar documents we want to retrieve, in this case we want to retrieve 2 similar documents. The similarity search will return the documents that are most similar to the query based on the embeddings generated by the embedding model.

for r in result:
     print(r.page_content)
    print(r.metadata)


retriever = vector_store.as_retriever()
docs = retriever.invoke("explain deep learning")

for doc in docs:
    print(doc.page_content)
